twitterFeed:
  consumerKey: ChQp4NPly1Jh2h2KzFiCYxej8
  consumerSecret: MHrgpq0Bu20DP8K6JJlhxu8ttrAoQdr9PRGyGoRMEU650uVUXK
  accessToken: 841696172259606528-EEBy80GObR3jBAtbnnEwdSxrTV12HJ3
  accessTokenSecret: y4xtqlWomS6kVmAGcV8TdWWX7p34Tpk8Bu9quBiblAARg