name: spacelaunchnow_flutter
description: A new Space Launch Now flutter application.
version: 2.2.2+1

dependencies:
  flutter:
    sdk: flutter
  intl: "^0.15.6"
  material_search: "^0.2.5"
  share: "^0.4.0"
  shared_preferences: "^0.5.4+3"

  # https://pub.dartlang.org/packages/firebase_admob#-installing-tab-]
  firebase_admob: ^0.9.0+7
  firebase_messaging: '^5.0.2'
  firebase_analytics: '^1.0.0'
  url_launcher: '^3.0.1'
  in_app_purchase: ^0.2.1+4
  uri: "^0.11.1"
  cached_network_image: ^2.0.0-rc
  rxdart: ^0.22.0
  sqflite: ^1.1.0
  flutter_staggered_grid_view: "^0.3.0"
  twitter: 1.0.0
  font_awesome_flutter: ^8.5.0
  material_design_icons_flutter: ^3.2.3695
  flutter_vector_icons: ^0.1.0
  rate_my_app: ^0.4.0

  # The following adds the Cupertino Icons Afont to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - config.yaml
    - assets/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
