name: spacelaunchnow_flutter
description: A new Space Launch Now flutter application.
version: 2.5.2+5

environment:
  sdk: '>=2.17.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
    
  intl: ^0.18.1
  share_plus: ^6.3.4

  # https://pub.dartlang.org/packages/firebase_admob#-installing-tab-]
  google_mobile_ads: ^3.0.0
  firebase_core: ^2.10.0
  firebase_messaging: ^14.4.1
  firebase_analytics: ^10.2.1
  url_launcher: ^6.1.10

  # IAP
  flutter_inapp_purchase: ^5.4.1

  uri: ^1.0.0
  cached_network_image: ^3.2.3
  flutter_staggered_grid_view: ^0.6.2
  video_player: ^2.6.1

  font_awesome_flutter: ^10.4.0
  material_design_icons_flutter: ^6.0.7096
  flutter_vector_icons: ^2.0.0
  rate_my_app: ^1.1.4
  yaml: ^3.1.1
  package_info: ^2.0.2
  youtube_player_flutter: ^8.1.2
  google_fonts: ^4.0.4
  quiver: ^3.2.1
  timeago: ^3.4.0
  shared_preferences: ^2.1.0

  # The following adds the Cupertino Icons Afont to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  logger: ^1.3.0
  firebase_core_platform_interface: ^4.6.0
  package_info_plus: ^3.1.2
  envied: ^0.3.0

dev_dependencies:
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:\
  fonts:
    - family: CustomSLN
      fonts:
        - asset:  fonts/CustomSLN.ttf

  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
