name: spacelaunchnow_flutter
description: A new Space Launch Now flutter application.
version: 2.5.0+3

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  share: ^2.0.4

  # https://pub.dartlang.org/packages/firebase_admob#-installing-tab-]
  google_mobile_ads: ^1.0.1
  firebase_core: ^1.11.0
  firebase_messaging: ^11.2.5
  firebase_analytics: ^9.0.5
  url_launcher: ^6.0.18

  # IAP
  flutter_inapp_purchase: ^5.1.2

  uri: ^1.0.0
  cached_network_image: ^3.2.0
  flutter_staggered_grid_view: ^0.6.0
  tweet_ui: ^3.0.1
  video_player: ^2.2.18

  dart_twitter_api: ^0.5.5+1
  font_awesome_flutter: ^9.2.0
  material_design_icons_flutter: ^5.0.6595
  flutter_vector_icons: ^1.0.0
  rate_my_app: ^1.1.1+1
  yaml: ^3.1.0
  package_info: ^2.0.2
  youtube_player_flutter: ^8.0.0
  google_fonts: ^2.2.0
  quiver: ^3.0.1+1
  timeago: ^3.2.0

  # The following adds the Cupertino Icons Afont to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  logger: ^1.1.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - config.yaml
    - assets/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:\
  fonts:
    - family: CustomSLN
      fonts:
        - asset:  fonts/CustomSLN.ttf

  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
