name: spacelaunchnow_flutter
description: A new Space Launch Now flutter application.
version: 2.6.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
    
  intl: ^0.19.0
  share_plus: ^7.2.2

  # https://pub.dartlang.org/packages/firebase_admob#-installing-tab-]
  google_mobile_ads: ^4.0.0
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  firebase_analytics: ^10.8.9
  url_launcher: ^6.2.5

  # IAP
  flutter_inapp_purchase: ^5.4.1

  uri: ^1.0.0
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  video_player: ^2.8.3

  font_awesome_flutter: ^10.7.0
  material_design_icons_flutter: ^7.0.7296
  flutter_vector_icons: ^2.0.0
  rate_my_app: ^2.0.0
  yaml: ^3.1.2
  youtube_player_flutter: ^9.0.0
  google_fonts: ^6.2.1
  quiver: ^3.2.1
  timeago: ^3.6.1
  shared_preferences: ^2.2.2

  # The following adds the Cupertino Icons Afont to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  logger: ^2.1.0
  firebase_core_platform_interface: ^5.0.0
  package_info_plus: ^5.0.1
  envied: ^0.5.3
  http: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:\
  fonts:
    - family: CustomSLN
      fonts:
        - asset:  fonts/CustomSLN.ttf

  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
