// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY28yZNAIX1QX1peT5uR0Rxz5WFk3VMgU',
    appId: '1:610310574961:web:0232dee568ace9edfedcd0',
    messagingSenderId: '610310574961',
    projectId: 'space-launch-now',
    authDomain: 'space-launch-now.firebaseapp.com',
    databaseURL: 'https://space-launch-now.firebaseio.com',
    storageBucket: 'space-launch-now.appspot.com',
    measurementId: 'G-NYSMR6NZKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfIVEUqV4IHI3hfQstqPWPyu9_qrlEkvE',
    appId: '1:610310574961:android:0705648b53af418ffedcd0',
    messagingSenderId: '610310574961',
    projectId: 'space-launch-now',
    databaseURL: 'https://space-launch-now.firebaseio.com',
    storageBucket: 'space-launch-now.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArmegAZD0BhF25rCji2vXmhSt3wRAtV6M',
    appId: '1:610310574961:ios:000f05cac2dcfe10',
    messagingSenderId: '610310574961',
    projectId: 'space-launch-now',
    databaseURL: 'https://space-launch-now.firebaseio.com',
    storageBucket: 'space-launch-now.appspot.com',
    androidClientId: '610310574961-52or82fnmqohinpab58n6epn4rvri2bt.apps.googleusercontent.com',
    iosClientId: '610310574961-g4aqhlvabn5eckam55kos5hoicrrtnvj.apps.googleusercontent.com',
    iosBundleId: 'me.spacelaunchnow.spacelaunchnow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArmegAZD0BhF25rCji2vXmhSt3wRAtV6M',
    appId: '1:610310574961:ios:000f05cac2dcfe10',
    messagingSenderId: '610310574961',
    projectId: 'space-launch-now',
    databaseURL: 'https://space-launch-now.firebaseio.com',
    storageBucket: 'space-launch-now.appspot.com',
    androidClientId: '610310574961-52or82fnmqohinpab58n6epn4rvri2bt.apps.googleusercontent.com',
    iosClientId: '610310574961-g4aqhlvabn5eckam55kos5hoicrrtnvj.apps.googleusercontent.com',
    iosBundleId: 'me.spacelaunchnow.spacelaunchnow',
  );
}
