/// Flutter icons CustomSLN
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomSLN
///      fonts:
///       - asset: fonts/CustomSLN.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CustomSLN {
  CustomSLN._();

  static const _kFontFam = 'CustomSLN';
  static const String? _kFontPkg = null;

  static const IconData starship =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData threedee_rotation =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
