---
name: Flutter Test
description: Run Flutter Test


runs:
  using: composite
  steps:
    - name: Pub Get
      shell: bash
      run: flutter pub get

    - name: Analyze
      shell: bash
      run: flutter analyze --no-fatal-infos

    - name: Test
      shell: bash
      run: flutter test