name: Flutter Test

on:
  pull_request:
    branches:
      - "**"

jobs:
  flutter_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'

      - name: Write .env
        id: write_file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: '.env'
          encodedString: ${{ secrets.ENV_FILE_DEV }}

      - name: Run Flutter Tests
        uses: ./.github/actions/flutter-test