name: Flutter Test

on:
  pull_request:
    branches:
      - "**"

jobs:
  flutter_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.4'

      - name: 'Create env file'
        run: |
          touch .env
          echo LL_API_KEY=${{ secrets.LL_API_KEY }} >> .env

      - name: Run Flutter Tests
        uses: ./.github/actions/flutter-test
