name: Flutter Test

on:
  pull_request:
    branches:
      - "**"

jobs:
  flutter_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'

      - name: Create env
        run: |
          echo ${{ secrets.ENV_FILE_DEV }} | base64 --decode > .env

      - name: Run Flutter Tests
        uses: ./.github/actions/flutter-test